### ISSUE TITLE
Performance: Big SVG sizes

### ISSUE THREAD

**Issue by AmraniCh** [himanshuk-dev/Himanshu-dot-dev#9]
Hello, nice work here! I came across your website and noticed very low loading on the first visit (about ~20 seconds) and very soon I figured out using the networks tool that your project's SVGs have huge sizes the bigger SVG is about 97 MB which is not good, I just want to take your attention to this!

**Comment by AmraniCh** [comment]
![image](https://github.com/himanshuk-dev/Himanshu-dot-dev/assets/49124992/f8f30291-1f67-482f-89d5-8e42d32b8d43)

**Comment by himanshuk-dev** [comment]
@AmraniCh Thank you for notifying. I am currently working on something. Would you like to work on this issue?
Please read [CONTRIBUTING.md](https://github.com/himanshuk-dev/Himanshu-dot-dev/blob/main/.github/CONTRIBUTING.md) before you proceed.

**Comment by himanshuk-dev** [comment]
Updated design to V2 which also involved updating all images to webp. Now the website isn't using gifs which were impacting performance. This issue has been resolved.

**Comment by AmraniCh** [comment]
Very good nice work!

**Comment by AmraniCh** [comment]
I'm also working on my website [amranich.dev](https://github.com/AmraniCh/amranich.dev) for a long time, but I will finish it very soon, I hope you check it out and tell me if you see something not right or need to improve!
